### ISSUE TITLE
Should the project use configuration for any "magic strings" 

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [FritzAndFriends/BlazorWebFormsComponents#105]
If there are JavaScript methods that need to be called by name, rather than store the name in a constant in the code, would it be better to use configuration? 

This would also allow the developer to call their own methods in place of the default - should they require it.

**Comment by hishamco** [comment]
Could you please provide an example?

**Comment by csharpfritz** [comment]
Added the JsScripts static class to contain these lookup values
