### ISSUE TITLE
JavaScript Interop Build tooling?

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#106]
We have a concept for some tooling to help lint or provide build checking to ensure that C# code that calls JavaScript is referencing script that exists

**Comment by VorTechS** [comment]
https://bridge.net/ might be what you were thinking of....

**Comment by VeronicaHex** [comment]
This is the current documentation for reference. https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1

**Comment by lythix** [comment]
We already have some great tools for generating code. t4 Templates and Roslyn. 
This article shows how to generate Javascript from C#, we could see if we can do the reverse. 
https://docs.microsoft.com/en-us/archive/msdn-magazine/2016/december/roslyn-generate-javascript-with-roslyn-and-t4-templates
