### ISSUE TITLE
CommandButton should trigger StateHasChanged when OnCommand runs

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#117]
See the AfterBlazorServerSide sample project in the Button/Index.razor demo.  It should not require the call to StateHasChanged in the OnCommand event handler to update the UI

**Comment by canhorn** [comment]
Does the OnCommand have to have a type of EventHandler<CommandEventArgs>?
Using EventCallback<CommandEventArgs> would allow for state changes to be propagated, but it would not have the same method declaration on usage.

**Comment by canhorn** [comment]
Here is more details on why EventCallback was created: https://github.com/dotnet/aspnetcore/issues/11035

**Comment by csharpfritz** [comment]
The only reason I considered EventHandler was to have some compatibility
with existing code.  EventCallback can certainly be used instead


Jeff
