### ISSUE TITLE
Need more unit tests for GridView GeneratedColumns

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#128]
It would be great to have unit tests to verify the GeneratedColumns handle:

- [ ] Add tests for different data classes to ensure reflection is properly used
- [ ] Add tests for classes with mixes of public, private, static properties, and fields

**Comment by grleachman** [comment]
Are you wanting to finish testing the current implementation, or are you expecting to extend this to using DisplayAttribute Annotations?

**Comment by csharpfritz** [comment]
My thinking was to add the validation so that the DisplayAttribute feature,
when added, can be assured that it isn't breaking the existing feature.

**Comment by hishamco** [comment]
The PR #201 address the second point, @csharpfritz could you please elaborate the first point, so I can add it to the same or another PR?

**Comment by csharpfritz** [comment]
I think that your test has this properly covered as it addresses static properties, fields, public and private scoped properties

**Comment by hishamco** [comment]
Also I added an indexer to be sure that they are ignored, one more thing may I need to test the collection properties, then we can close this one

**Comment by hishamco** [comment]
As expected there's a bug with collections properties, @csharpfritz please close this and I will open another issue

**Comment by csharpfritz** [comment]
Closing and redirecting to #203
