### ISSUE TITLE
Colors in markup

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#13]
In Web Forms, you were able to set attribute values for colors to either a color name or to an HTML hex color representation.  In our components, you're forced in a Color object

**Comment by Code-DJ** [comment]
Is this supported? WebForms uses TypeConverter to handle this, but it appears this isn't fully implemented in Razor. Am I missing something?

https://github.com/dotnet/aspnetcore/issues/8493

**Comment by csharpfritz** [comment]
One idea I had considered was wrapping the `System.Drawing.Color` type as `WebColor` and provide and implicit conversion from string to `WebColor` that inspects and does the appropriate conversion.

`WebColor` should simply delegate to the `System.Drawing.Color` object while providing a good `ToHtmlString()` method that allows us to format the `WebColor` for our markup styles.

We could use the same static type architecture trick that we are using in RepeatLayout to deliver this feature
