### ISSUE TITLE
LinkButton documentation

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#134]
We need an article in the `docs` folder for the LinkButton.

**Comment by hishamco** [comment]
I already added this in my previous PR ;)

**Comment by hishamco** [comment]
FYI https://github.com/FritzAndFriends/BlazorWebFormsComponents/blob/dev/docs/LinkButton.md

**Comment by grleachman** [comment]
can this be closed?

**Comment by csharpfritz** [comment]
Done...  Good catch!
