### ISSUE TITLE
@bind attribute cannot be used inside GridView item template.

### ISSUE THREAD

**Issue by TPIvan** [FritzAndFriends/BlazorWebFormsComponents#159]
**Sumary**
When I use
 
    <input type="text" @onblur="StateHasChanged" @bind="item.Name" />
inside TemplateField/ItemTemplate I am getting

>Error	CS1662	Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type	
>Error	CS1973	'EventCallbackFactory' has no applicable method named 'CreateBinder' but appears to have an extension method by that name. Extension methods cannot be dynamically dispatched. Consider casting the dynamic arguments or calling the extension method without the extension method syntax.	

When the code is replace by "full syntax"

    <input type="text" value="@item.Name" @onchange="@((ChangeEventArgs __e) => {  ((ExpLocItem )item).Name = __e.Value.ToString(); })" @onblur="StateHasChanged" />
It works as expected.

**Full example:**

    @page "/Bugtest"
    <h3>bugtest</h3>
    <input type="text" @onblur="StateHasChanged" @bind="expLocItems[0].Name" />
    <GridView DataSource="@expLocItems" AutogenerateColumns="true">
        <Columns>
            <TemplateField >
                <ItemTemplate Context="item">
                    @*<input type="text" value="@item.Name" @onchange="@((ChangeEventArgs __e) => {  ((ExpLocItem )item).Name = __e.Value.ToString(); })" @onblur="StateHasChanged" />*@
                    <input type="text" @onblur="StateHasChanged" @bind="item.Name" />
                </ItemTemplate>
            </TemplateField>
        </Columns>
    </GridView>
    
    @code {
    
        List<ExpLocItem> expLocItems = new List<ExpLocItem>(){
                            new ExpLocItem("Petr", 1),new ExpLocItem("Josef", 3),new ExpLocItem("Vintir",5),new ExpLocItem("Franta", 9) };
    
    
        public class ExpLocItem
        {
            public string Name { get; set; }
            public int Number { get; set; }
    
            public ExpLocItem(string name, int number)
            {
                Name = name; Number = number;
            }
        }
    }

By the way I like the web forms library Idea and appreciate the implementation speed.

**Comment by grleachman** [comment]
I have committed a fix and a test, 
However the ComponentUnderTest does not seem to like the @bind attribute.
I have submitted a bug report to [egil](https://github.com/egil/bunit/issues/96)

**Comment by csharpfritz** [comment]
Closing with the PR submitted by @grleachman
