### ISSUE TITLE
Need a logo

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#175]
We could really use a logo for this project to put on the NuGet registry and to use here on GitHub

**Comment by hishamco** [comment]
I can share one, but I suggest to tweet about this to encourage the designers who love OSS and passionate about Blazor & WebForms to design one for this project

**Comment by csharpfritz** [comment]
I have an artist finishing a logo in the next day or two



Jeff

**Comment by csharpfritz** [comment]
Merging logo into docs and package publication
