### ISSUE TITLE
Make the Docs folder navigable

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#178]
We need to be able to navigate around the documentation in the docs folder.  

Also:  we need a link to the docs on the Readme for this repository

The docs are being published to GitHub pages at:  https://fritzandfriends.github.io/BlazorWebFormsComponents/

**Comment by crazy-max** [comment]
@csharpfritz We could use [Mkdocs Material](https://squidfunk.github.io/mkdocs-material/) to create the documentation website. As I said on your stream, I use it on some of my projects and it's pretty neat and straight forward:

* https://github.com/crazy-max/diun/tree/master/docs
* https://crazy-max.github.io/diun/

I will open a draft PR and keep you in touch about the implementation.

**Comment by AlexHedley** [comment]
Not to step on the fantastic work @crazy-max did with mkdocs, but just for comparison here's the docfx version
The only addition is the API docs

https://alexhedley.github.io/BlazorWebFormsComponents/

**Comment by crazy-max** [comment]
@AlexHedley That's nice too! Thanks for sharing!

**Comment by csharpfritz** [comment]
That is REALLY cool @AlexHedley -- thank you for sharing!
