### ISSUE TITLE
Investigate:  Can we simplify DataTable datasources?

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#191]
Can we either wrap our components or improve the DataBinding code to detect a DataTable / DataSet and execute the AsDynamicEnumerable() extension method internally to the component?

We need to simplify the signature of the controls so that using a DataTable / DataSet **ONLY** requires the same markup or API interaction as the original control

**Comment by hishamco** [comment]
> Can we either wrap our components or improve the DataBinding code to detect a DataTable / DataSet and execute the AsDynamicEnumerable() extension method internally to the component?

That's exactly what I wanna do ;)

> We need to simplify the signature of the controls so that using a DataTable / DataSet ONLY requires the same markup or API interaction as the original control

This can happen if we fix the original issue which is make `DataSource`  property returns `Object` instead of `IEnumerable<T>`, You can assign this to me and I will start on working to refactor this
