### ISSUE TITLE
Bug: Revise the Site.master in the BeforeWebForms project

### ISSUE THREAD

**Issue by mpaulosky** [FritzAndFriends/BlazorWebFormsComponents#199]
### Revise the Site.master in the BeforeWebForms project

To eliminate issues found with adding the TreeView menu on #186 

- [ ] Menu expands to full screen when zooming and increasing the browser size.

- [ ] Menu expands to full screen when reducing the browser size.

**Comment by mpaulosky** [comment]
I have a solution for this issue.

**Comment by hishamco** [comment]
Can you submit a PR for it?
