### ISSUE TITLE
Complete implementing AdRotator attributes

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#209]
Some attributes for the AdRotator that need to be completed:

- [ ] All Style attributes, implementing IHasStyle
- [ ] KeywordFilter

**Comment by hishamco** [comment]
I can work on this one ...

**Comment by csharpfritz** [comment]
Assigned

**Comment by hishamco** [comment]
- [ ]  All Style attributes, implementing IHasStyle

- [ ]  KeywordFilter
