### ISSUE TITLE
DataList: RepeatColumns needs to be supported and support more than 1 column

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#21]

**Comment by grleachman** [comment]
annoying little issue here..

[Attribute Value Conflicts](https://github.com/grleachman/BlazorWebFormsComponents/commit/119065d09d2eb20e7ff3361ad49d14febb35a823#diff-2bf2259c65ec6fdb4a33a31f47132ce9)

Adding RepeatDirection has caused a conflict with GridLines

There's now an ugly problem where the static enums require the markup to be messy, requiring

```Gridlines="Enums.GridLines.Horizontal"``` 
```RepeatDirection="Enums.RepeatDirection.Enum.Horizontal"```

This is going to be painful for migration.

**Comment by csharpfritz** [comment]
Maybe these don't need to be static enums and can be regular enums

**Comment by grleachman** [comment]
The alternative is to not have individual attribute enums...
`Enums.Gridlines.Horizontal` and
`Enums.RepeatDirection.Horizontal`

but rather use
`Enums.**DataList**.Horizontal`

**Comment by csharpfritz** [comment]
Merged.  Thank you for the work on this complex issue
