### ISSUE TITLE
HiddenField - Missing Attributes?

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#218]
Let's investigate the following attributes and add them if appropriate:

- [ ] OnDataBinding
- [ ] Visible  -- This feels strange since the field is a HIDDEN field

**Comment by hishamco** [comment]
I will have a look to this too ...

**Comment by hishamco** [comment]
>  Visible -- This feels strange since the field is a HIDDEN field

This is strange because the property is belong to `Control`, so no action needed here

**Comment by hishamco** [comment]
Also this
