### ISSUE TITLE
Image control needs style and some attributes

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#227]
Need to implement IHasStyle and attributes:

- [ ] GenerateEmptyAlternateText
- [ ] ImageAlign
- [ ] ToolTip
- [ ] Visible

**Comment by hishamco** [comment]
- [x] GenerateEmptyAlternateText
- [ ] ImageAlign
- [x] ToolTip
- [x] Visible
