### ISSUE TITLE
ImageButton is missing Style and other attributes

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#229]
ImageButton needs to implement IHasStyle and these attributes:

- [ ] Enabled
- [ ] ImageAlign
- [ ] OnDataBinding
- [ ] ToolTip
- [ ] Visible

**Comment by hishamco** [comment]
The PR #235 fixes all except `OnDataBinding` which we need to agree with before we applied to all the components

**Comment by hishamco** [comment]
- [x] Enabled
- [ ] ImageAlign
- [ ] OnDataBinding
- [x] ToolTip
- [x] Visible

**Comment by hishamco** [comment]
I think this is done
