### ISSUE TITLE
Modifying style properties after style is calculated is not reflected

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#241]
Example:  update the border property after a component has been rendered and the component will not update with the new border style

**Comment by csharpfritz** [comment]
This feels like it can be exposed as a unit test

**Comment by hishamco** [comment]
I will have a look what the original cause for the bug I faced before

**Comment by hishamco** [comment]
I'm closing this because there's no bug, but the issue was with the border style
