### ISSUE TITLE
Rename IHasXXXStyle to IXXXStyle

### ISSUE THREAD

**Issue by hishamco** [FritzAndFriends/BlazorWebFormsComponents#250]
While submitting the pr #243, I notice that we have some `IHasXXXStyle` interfaces, the naming is little bit not suited from API design point of you, what I'm suggesting is to replace them to `IXXXStyle` which is more clear

**Comment by csharpfritz** [comment]
This was an internal API, and should not have been exposed to the consumers.  For that, we could have kept a quirky name.  

Not a problem to change
