### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by htmlsplash** [FritzAndFriends/BlazorWebFormsComponents#269]
I see no updates in past 2 years, is this project dead? What's the status of this project?

**Comment by zachrybaker** [comment]
@csharpfritz can you respond? Seems like you lost interest or time to do this?

**Comment by csharpfritz** [comment]
There's been a different direction from the .NET team on how they want to encourage folks to migrate to Blazor and .NET 6+

Additionally, we received very little feedback from the community, and I was carrying the project myself for a while.  If there is interest, I can certainly update this to the latest .NET and start discussing integrating more features.

I would look for more folks to get involved with pushing this project forward

**Comment by hishamco** [comment]
I'm with you @csharpfritz, I'm still a WebForms fan and I can move this project forward if I become a member with write access permission

**Comment by foluis** [comment]
Multiple UI components projects are available, and I have experience with Radzen and MudBlazor. This post discusses some of these projects.
https://www.claudiobernasconi.ch/2023/05/25/8-free-and-open-source-blazor-ui-libraries/

**Comment by csharpfritz** [comment]
> Multiple UI components projects are available, and I have experience with Radzen and MudBlazor. This post discusses some of these projects. [claudiobernasconi.ch/2023/05/25/8-free-and-open-source-blazor-ui-libraries](https://www.claudiobernasconi.ch/2023/05/25/8-free-and-open-source-blazor-ui-libraries/)

This is not a typical Blazor component library... but rather a library that assists with the migration of WebForms projects by providing the same tag structure as the original ASP.NET Web Forms and renders the same HTML as those components

**Comment by gabrielacos** [comment]
I used to work with web form and is still my favorite of creating application, any new development or UI. 

I haven't tested this project but I receieve a lot of small updated and may be still development.

https://github.com/Jurioli/Blazor.WebForm.Components

**Comment by zachrybaker** [comment]
> There's been a different direction from the .NET team on how they want to encourage folks to migrate to Blazor and .NET 6+

@csharpfritz can you elaborate?  As of today, there are MS articles that link to this very repo....every indication is that (a) MS doesn't really support/guide a migration from web forms to anything and (b) but they do suggest a couple ideas and reference your repo.
