### ISSUE TITLE
Add Unit Tests for Login Control

### ISSUE THREAD

**Issue by hugodahl** [FritzAndFriends/BlazorWebFormsComponents#43]
Add unit tests for the login controls from issue #41, and implemented in PR #42.

**Comment by hishamco** [comment]
I may take this one if all the controls / components are teastable

**Comment by grleachman** [comment]
@hishamco are you likely to push any code on this one soon?

**Comment by hishamco** [comment]
I'm still facing a restore issue due Internet connection issue, if you want to submit a PR for this no problem

**Comment by hishamco** [comment]
FYI I'm working on PR for this, hope to submit it ASAP ...
