### ISSUE TITLE
ListView:  ModelBinding sample is not working

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#52]

**Comment by grleachman** [comment]
see [ListView](https://github.com/FritzAndFriends/BlazorWebFormsComponents/blob/dev/docs/ListView.md) for the Implementation that is being aimed for.

also see [System.Web.UI.WebControls.ListView](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.webcontrols.listview?view=netframework-4.8) for `asp:ListView` class inheritance and interfaces implemented.
