### ISSUE TITLE
TreeView: DataBinding strategy

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#55]
Discussion:

A recursive TreeNode binding strategy may more easily help enable other data-models beyond XML to bind data to the TreeView.

**Comment by marin-bratanov** [comment]
I think it can also ease the creation of the bindings - the loops that create nodes can count their level (depth) and so you can easily extract field names or other info from a List of bindings by their index.

**Comment by hishamco** [comment]
I already did some data binding with AD organizational units and their children using recursive strategy, I'm glad to share my thoughts, and doing some exterminates after looking to the Tree View component
