### ISSUE TITLE
Unable to restore Project Packages

### ISSUE THREAD

**Issue by hishamco** [FritzAndFriends/BlazorWebFormsComponents#71]
@csharpfritz I want to do some PRs, but till now I'm not able to restore the project packages using `dotnet restore`

Any guidance on that? This is first OSS project I faced this issue

**Comment by csharpfritz** [comment]
What errors are you getting?  Can you share the error report so that we can debug?

**Comment by csharpfritz** [comment]
There is a nuget.config in the `dev` branch that SHOULD configure you appropriately.

You should be able to `dotnet restore` from the `src` folder and start working with the library and Blazor samples.

The BeginWebForms application will require you to nuget restore from samples/BeforeWebForms.

**Comment by hishamco** [comment]
> There is a nuget.config in the dev branch that SHOULD configure you appropriately.

What kind of configuration? coz I just run the restore command directly

Thanks

**Comment by csharpfritz** [comment]
The `nuget.config` file in the root of the repository should configure the packages folder for the BeginWebForms project if you need to refer back to the Web Forms code.

The .NET Core / .NET Standard projects in `src` and `samples` should restore just fine with a `dotnet restore` command in their project folders.

**Comment by hishamco** [comment]
Let me try now, thanks a lot Jeffrey

**Comment by csharpfritz** [comment]
@hishamco -- are  you still having a problem?

**Comment by hishamco** [comment]
Thanks for asking Jeff, ya still, but I'm trying to check if it's my internet connection issue or NuGet feed links, coz I got some of `System.TimoutException`

**Comment by csharpfritz** [comment]
Closing and will re-open if there is an issue identified

**Comment by hishamco** [comment]
![Restore](https://user-images.githubusercontent.com/3237266/74760919-336e7f00-528c-11ea-8511-1a8bd684b5b2.png)

@csharpfritz attached error. Today the Internet becomes better at my end, but still I'm facing a restoring issue

**Comment by hishamco** [comment]
Finally it works, but the `BeforeWebForms` need to be unloaded no problem while the new stuff it works

It is time to check the issues and start PRs ;)
