### ISSUE TITLE
FormView component

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#82]
- [x] Initial documentation from docs.microsoft.com
- [x] Build a sample page in BeforeWebForms project
- [x] Component
- [x] Read-only mode
- [x] Command button support
- [x] EditItemTemplate
- [x] InsertItemTemplate
- [x] Event Handlers

Need to trigger a Delete on the DataSource when a CommandName "Delete" is triggered.
https://docs.microsoft.com/dotnet/api/system.web.ui.webcontrols.formview?view=netframework-4.8#data-operations

**Comment by hishamco** [comment]
What's the progress of this? What's remaining to work with?

**Comment by csharpfritz** [comment]
Still working on the Read-only mode, and need to be able to trigger and handle Commands

**Comment by csharpfritz** [comment]
Need to still add InsertItemTemplate and DeleteItemTemplate

**Comment by hishamco** [comment]
Do you need a help on the above templates?
