### ISSUE TITLE
Can we create an Eval() method for templates?

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#85]
This might be a stretch, but what about writing a method that uses reflection across the @Context item in a template to output a property specified in the same way that Eval() worked in Web Forms?

From Web Forms:  `<#: Eval("EmployeeName") %>`
converts to:     `@Eval("EmployeeName")`

**Comment by hishamco** [comment]
It's good idea for those who wanna convert binding syntax from WebForms, but if the `@context` is strongly type I prefer to use it rather than doing a reflection stuff

**Comment by csharpfritz** [comment]
Oh yes, the strongly-typed reference should be the recommended way to solve this.

This feature should be considered JUST to make an automated conversion easier.

**Comment by hishamco** [comment]
> This feature should be considered JUST to make an automated conversion easier.

Agree

**Comment by csharpfritz** [comment]
Completed an initial implementation that uses a CascadingValue to populate the value inside of an Eval component that is dynamically added to when the Eval() method is called.

Also added a format argument to the Eval method.

The CascadingParameter needs to be carried through to the other databound components.  Should try to adhere to the `DataBinder.Eval` syntax defined here:  https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.databinder.eval?view=netframework-4.8

**Comment by csharpfritz** [comment]
Thinking more about this approach, we could probably write something to handle the `Item.` and `BindItem.` syntax of the databinder as well
