### ISSUE TITLE
Improve Test Coverage on ListView Grouping

### ISSUE THREAD

**Issue by grleachman** [FritzAndFriends/BlazorWebFormsComponents#89]
I wasn't happy with the test coverage.
Having gone back to review I find it's lacking, and the behaviour still doesn't mimic the WebForms correctly specifically around ItemSeparator.

There's an interesting anomaly on groups of 7 grouped by 3 where the ItemSeparator is added after the last item twice. Not sure why this is, but presume it needs to be mimicked, and will investigate other combinations.

```
GroupStart
seven Widget
ItemSeparator
ItemSeparator
GroupEnd
```
UPDATE
> Having reviewed this. I found that the anomaly was intended behaviour. for a 7 items grouped in 6 layout, there would be 6 elements in the first group with 5 separators, and 1 element in the 2nd group with still 5 separators.
>
> 7 x 6 -> ``` I s I s I s I s I s I G I s s s s s ```

**Comment by hishamco** [comment]
Are you working on this one?
